export default {
  SPINNER_PRIMARY: '#AAABAC',
  ALERT: '#fff',
  BUTTON_COLOR: '#239ED0',
  WHITE_COLOR: '#FFF',
  BLACK_COLOR: '#000',
  GREY_COLOR: '#272727',
  LIGHT_GREY_COLOR: '#707070',
  BACKGROUND_COLOR: '#D2D8CF',
  INPUT_COLOR:'#D2D8CF',
};
